-- AUTO-GENERATED by tools/watch_marker_images.ps1 (or gen_marker_manifest.sh) -- do not edit by hand.
-- WoW cannot enumerate a folder at runtime, so this lists every image file in
-- media\\marker-images\\ for the Center Marker / Pressed Indicator dropdowns.
-- Rewritten automatically whenever the folder changes; then /reload in-game.
GSETracker_MarkerImageFiles = {
  "Alliance-Shiny.png",
  "Alliance.png",
  "Crosshairs001.png",
  "Crosshairs002.png",
  "Crosshairs003.png",
  "Crosshairs004.png",
  "Crosshairs005.png",
  "Crosshairs006.png",
  "Crosshairs007.png",
  "Crosshairs008.png",
  "Dot.png",
  "GSE_Tracker_Round.png",
  "GSE_Tracker.png",
  "Horde-Shiny.png",
  "Horde.png",
  "X.png",
}
