-- AUTO-GENERATED by tools/gen_marker_manifest.sh -- do not edit by hand.
-- WoW cannot enumerate a folder at runtime, so this lists every image file in
-- media\\marker-images\\ for the Center Marker / Pressed Indicator dropdowns.
-- Re-run tools/gen_marker_manifest.sh after adding or removing files there.
GSETracker_MarkerImageFiles = {
  "Alliance.png",
  "Crosshairs001.png",
  "Crosshairs002.png",
  "Crosshairs003.png",
  "Crosshairs004.png",
  "Crosshairs005.png",
  "Crosshairs006.png",
  "Crosshairs007.png",
  "Crosshairs008.png",
  "Crosshairs009.png",
  "Crosshairs010.png",
  "Dot.png",
  "Horde.png",
  "X.png",
  "YingYang.png",
}
