#!/usr/bin/env bash
# Regenerate utils/marker_manifest.lua from the PNG/TGA files in media/marker-images/.
#
# WoW addons cannot list a folder's contents at runtime (sandbox limitation), so the
# Center Marker / Pressed Indicator dropdowns read this generated manifest to know which
# image files exist. Re-run this script after adding or removing files in that folder:
#
#     bash tools/gen_marker_manifest.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."

src="media/marker-images"
out="utils/marker_manifest.lua"

{
  echo "-- AUTO-GENERATED by tools/gen_marker_manifest.sh -- do not edit by hand."
  echo "-- WoW cannot enumerate a folder at runtime, so this lists every image file in"
  echo "-- media\\\\marker-images\\\\ for the Center Marker / Pressed Indicator dropdowns."
  echo "-- Re-run tools/gen_marker_manifest.sh after adding or removing files there."
  echo "GSETracker_MarkerImageFiles = {"
  for f in "$src"/*.png "$src"/*.tga; do
    [ -e "$f" ] || continue
    echo "  \"$(basename "$f")\","
  done
  echo "}"
} > "$out"

count=$(grep -c '\.png"\|\.tga"' "$out" || true)
echo "Wrote $out ($count file(s))."
