<#
.SYNOPSIS
  Auto-regenerate utils\marker_manifest.lua whenever media\marker-images\ changes.

.DESCRIPTION
  WoW addons cannot list a folder's files at runtime, so the Center Marker / Pressed
  Indicator dropdowns read a generated manifest of filenames. This watcher rewrites that
  manifest whenever an image is added, removed, or renamed in media\marker-images\ -- so
  after you change files you just /reload in-game and the new names appear. Works with ANY
  filename (no CrosshairsNNN convention needed).

  It POLLS the folder (every couple of seconds) rather than using FileSystemWatcher events,
  which are unreliable in a headless background process. Leave it running in a window, or
  auto-start it at logon (see AUTO-START below).

.EXAMPLE
  pwsh -ExecutionPolicy Bypass -File tools\watch_marker_images.ps1
  # or, on stock Windows PowerShell:
  powershell -ExecutionPolicy Bypass -File tools\watch_marker_images.ps1

.NOTES
  AUTO-START AT LOGON (run once, from the addon root). Uses -WorkingDirectory + a RELATIVE
  -File path because this addon's absolute path contains backticks/spaces that break
  command-line quoting:
    $exe = (Get-Command pwsh -ErrorAction SilentlyContinue).Source
    if (-not $exe) { $exe = "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" }
    $a = New-ScheduledTaskAction -Execute $exe `
           -Argument '-WindowStyle Hidden -ExecutionPolicy Bypass -File tools\watch_marker_images.ps1' `
           -WorkingDirectory $PWD
    $t = New-ScheduledTaskTrigger -AtLogOn
    Register-ScheduledTask -TaskName "GSE_Tracker marker watcher" -Trigger $t -Action $a -RunLevel Limited -Force
  Remove later:
    Unregister-ScheduledTask -TaskName "GSE_Tracker marker watcher" -Confirm:$false
#>
param([int]$IntervalSeconds = 2)
$ErrorActionPreference = 'Stop'

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$src  = Join-Path $root 'media\marker-images'
$out  = Join-Path $root 'utils\marker_manifest.lua'

function Get-MarkerFiles {
    if (-not (Test-Path $src)) { return @() }
    return @(Get-ChildItem -Path $src -File -ErrorAction SilentlyContinue |
             Where-Object { $_.Extension -in '.png', '.tga' } |
             Sort-Object Name)
}

function Write-MarkerManifest {
    param($files)
    $lines = @(
        '-- AUTO-GENERATED by tools/watch_marker_images.ps1 (or gen_marker_manifest.sh) -- do not edit by hand.'
        '-- WoW cannot enumerate a folder at runtime, so this lists every image file in'
        '-- media\\marker-images\\ for the Center Marker / Pressed Indicator dropdowns.'
        '-- Rewritten automatically whenever the folder changes; then /reload in-game.'
        'GSETracker_MarkerImageFiles = {'
    )
    foreach ($f in $files) { $lines += ('  "' + $f.Name + '",') }
    $lines += '}'
    # WriteAllLines = UTF-8 WITHOUT BOM (a BOM would break the Lua file).
    [System.IO.File]::WriteAllLines($out, [string[]]$lines, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host ("[{0}] marker_manifest.lua updated ({1} file(s))" -f (Get-Date -Format HH:mm:ss), $files.Count)
}

$files = Get-MarkerFiles
Write-MarkerManifest $files               # initial sync on startup
$last = ($files | ForEach-Object Name) -join '|'

Write-Host "Watching $src every ${IntervalSeconds}s -- press Ctrl+C to stop."
while ($true) {
    Start-Sleep -Seconds $IntervalSeconds
    $files = Get-MarkerFiles
    $sig = ($files | ForEach-Object Name) -join '|'
    if ($sig -ne $last) {
        $last = $sig
        try { Write-MarkerManifest $files } catch { Write-Host "regen error: $_" }
    }
}
